namespace: caseraw
name: machinemsg
version: 1.0.6
readme: README.md
authors:
    - Kasra Amirsarvari <@kasraMforce
description: Set the machine motd and banner message 
license:
    - GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: https://github.com/Caseraw/psa_hackaton
documentation: https://github.com/Caseraw/psa_hackaton
homepage: https://github.com/Caseraw/psa_hackaton
issues: https://github.com/Caseraw/psa_hackaton/issues
build_ignore: []
